name: Build concatenated filter

on:
	push:
		branches: [ main ]

	schedule:
	- cron: "0 0 * * *"

	workflow_dispatch:

jobs:
	build:
		name: Build
		runs-on: ubuntu-latest
		steps:
		- name: Download repo
			uses: actions/checkout@v3

		- name: Runnning build/generation script
			shell: bash
			run: |
				python3 ./script.py

		- name: Generate tag name
			run: echo "TAG_NAME=$(date +%F-%H-%M)" >> $GITHUB_ENV

		- name: Release filter lists
			uses: softprops/action-gh-release@v1
			with:
				files: concatenated_list.txt
				name: Automatic list generation
				tag_name: ${{ env.TAG_NAME }}
			env:
				GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

		- name: Delete older releases
			uses: dev-drprasad/delete-older-releases@v0.2.1
			with:
				keep_latest: 2
				delete_tags: true
			env:
				GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

		- name: Upload log files
			uses: actions/upload-artifact@v3
			with:
				name: Logs
				path: logs/*.log
			if: ${{ always() }}
